################################################################################
#
#  Github actions trigger (workflow script) for building Macaulay2
#
#    See https://help.github.com/en/actions for the documentation.
#
################################################################################

name: Build and Test Macaulay2

on:
  # trigger a test quick build at both PR (on dev)
  # and pushing to master (after merging or by Dan or Mike)
  push:
    branch:
      - master
  pull_request:
    branch:
      - developement
  schedule:
    # cron time in UTC; set to 6a EDT
    - cron: '0 10 * * *'

env:
#  CMAKE_VERSION: 3.17
#  NINJA_VERSION: 1.9.0
  # needs BuildFast
  BUILD_TYPE: Release

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      # eventually make this true
      fail-fast: false
      matrix:
        config:
#          - {
#            name: "macOS-latest cmake gcc9",
#            artifact: "macOS-gcc.tar.xz",
#            os: macos-latest,
#            cc: "gcc-9", cxx: "g++-9",
#            build-system: "cmake"
#          }
          - {
            name: "macOS-latest automake gcc9",
            artifact: "macOS-gcc.tar.xz",
            os: macos-latest,
            cc: "gcc-9", cxx: "g++-9",
            make: "gmake",
            build-system: "automake"
          }
#          - {
#            name: "Ubuntu-latest cmake gcc9",
#            artifact: "Ubuntu.tar.xz",
#            os: ubuntu-latest,
#            cc: "gcc-9", cxx: "g++-9",
#            build-system: "cmake"
#          }
          - {
            name: "Ubuntu-latest automake gcc9",
            artifact: "Ubuntu.tar.xz",
            os: ubuntu-latest,
            cc: "gcc-9", cxx: "g++-9",
            make: "make",
            build-system: "automake"
          }

    steps:
      - uses: actions/checkout@v1  # this set up the virtual environment, which has a whole lot
                                   # as of this writing: gcc9, clang10, cmake3.17, homebrew...

      - name: Install missing dev tools (brew)
        id: get_dev_tools_brew
        if: ${{ runner.os == 'macOS' }}
        # autoconf, libtool are already in the virtual env
        run: brew install ninja pkg-config autoconf automake gnu-tar libtool yasm make

      - name: Install libraries (brew)
        id: get_dev_libraries_brew
        if: ${{ runner.os == 'macOS' }}
        # mpfr, gdbm, libmpc, xz are already in the virtual env
        run: brew install boost flint ntl mpir bdw-gc libatomic_ops glpk libomp eigen ncurses

      - name: Install missing dev tools (apt-get)
        id: get_dev_tools_aptget
        if: ${{ runner.os == 'Linux' }}
        # make is really gmake
        run: sudo apt-get install -y ninja-build

      - name: Install libraries (apt-get)
        id: get_dev_libraries_aptget
        if: ${{ runner.os == 'Linux' }}
        run: sudo apt-get install -y -q apt-get install -y -q sudo autoconf bison curl emacs fflas-ffpack flex g++ gcc gfortran install-info libatomic-ops-dev libboost-dev libc6-dev libcdd-dev libgc-dev libgdbm-dev libgivaro-dev libglpk-dev libgmp3-dev libgtest-dev liblapack-dev liblzma-dev libmpc-dev libmpfr-dev libncurses-dev libncurses5-dev libntl-dev libreadline-dev libtool libxml2-dev libz-dev make openssh-server patch pinentry-curses pkg-config time unzip xbase-clients yasm zlib1g-dev polymake w3c-markup-validator git dpkg-dev gfan libeigen3-dev libtool-bin

      - name: Install gtest from source
        id: step_gtest
        run: |
          git clone https://github.com/google/googletest.git
          mkdir googletest/build && cd googletest/build
          CXX=${{matrix.config.cxx}} CC=${{matrix.config.cc}} cmake .. -G"Ninja" -DBUILD_SHARED_LIBS=ON
          ninja
          sudo ninja install
          pwd

      - name: Configure Macaulay2 (cmake)
        id: step_configure_cmake
        if: ${{ matrix.config.build-system == 'cmake' }}
        run: |
          mkdir M2/BUILD/cicd
          cd M2/BUILD/cicd
          CXX=${{matrix.config.cxx}} CC=${{matrix.config.cc}} \
          cmake -S../.. -B. -G"Ninja" -DCMAKE_BUILD_TYPE=Release

      - name: Build Macaulay2 (cmake)
        id: step_build
        if: ${{ matrix.config.build-system == 'cmake' }}
        run: |
          cmake --build M2/BUILD/cicd --parallel 4 --target build-libraries build-programs
          cmake --build M2/BUILD/cicd --parallel 4 --target install-packages
          cmake --build M2/BUILD/cicd --parallel 4 --target M2-emacs

      - name: Configure Macaulay2 (automake)
        id: step_configure_automake
        if: ${{ matrix.config.build-system == 'automake' }}
        run: |
          cd M2
          ${{matrix.config.make}} get-tools
          ${{matrix.config.make}} -f Makefile
          mkdir BUILD/cicd
          cd BUILD/cicd
          CXX=${{matrix.config.cxx}} CC=${{matrix.config.cc}} \
          ../../configure --enable-download --enable-build-libraries="readline"

      - name: Build Macaulay2 (automake)
        id: step_build_automake
        if: ${{ matrix.config.build-system == 'automake' }}
        run: |
          cd M2/BUILD/cicd
          ${{matrix.config.make}}

      - name: Run Tests
        id: step_run_tests
        run: echo "Placeholder. Don't do anything for now"
